@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes view command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:ViewWindow draws calendar;
:MainWindow opens ViewWindow;
stop
@enduml
